<?php

$intl_list = array('intl','us');

$brands_list = array(
		     0 => '',
		     'Amante' => 'Amante',
		     'Bw!tch' => 'Bw!tch',
		     'Enamor' => 'Enamor',
		     'Hanes' => 'Hanes',
		     'Hollywood Fashion Secrets' => 'Hollywood Fashion Secrets',
		     'Inaya' => 'Inaya',
		     'Jockey' => 'Jockey',
		     'Lovable' => 'Lovable',
		     'Triumph' => 'Triumph',
		     'Zivame' => 'Zivame'
		     );